# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macOS 10.14'

variables:
  - group: iOS_calc

jobs:
- job: build
  displayName: Building .ipa
  steps:
  - script: pod install --project-directory=SwiftCalculator-master
    displayName: 'Install AppCenter'
    
  - task: Xcode@5
    inputs:
      xcWorkspacePath: 'SwiftCalculator-master/Calculator.xcworkspace'
      scheme: 'Calculator'
      sdk: 'iphoneos'
      configuration: 'Release'
      xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
      
 - task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:OutputPath=$(Build.ArtifactStagingDirectory)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: '$(p12name)'
      certPwd: '$(p12pass)'
      keychain: 'temp' # Options: default, temp, custom
      deleteCert: true
  - task: CopyFiles@2
    displayName: Stage ipa
    inputs:
      contents: '$(BIN_DIR)/*.ipa'
      targetFolder: '$(build.artifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: Publish ipa
    inputs:
      pathToPublish: '$(build.artifactStagingDirectory)'
      artifactName: 'drop'

