# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macOS 10.14'

variables:
  - group: iOS_calc

steps:

- script: |
  pod install
  displayName: 'Install AppCenter'

- task: Xcode@5
  inputs:
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
    
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: '$(p12name)'
    certPwd: '$(p12pass)'
    keychain: 'temp' # Options: default, temp, custom
    deleteCert: true

