# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macOS 10.14'

variables:
  - group: iOS_calc

steps:

- script: |
    pod install --project-directory=SwiftCalculator-master
  displayName: 'Install AppCenter'

- task: Xcode@5
  inputs:
    xcWorkspacePath: 'SwiftCalculator-master/Calculator.xcworkspace'
    scheme: 'Calculator'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
    
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: '$(p12name)'
    certPwd: '$(p12pass)'
    keychain: 'temp' # Options: default, temp, custom
    deleteCert: true

# App Center distribute
 # Distribute app builds to testers and users via Visual Studio App Center
 - task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'VSAC'
    appSlug: 'mjasha/Simple-Calculator'
    appFile: 'Calculator.app'
    releaseNotesOption: 'input'
    releaseNotesInput: 'This is simple calculator'
    isMandatory: true
    destinationType: 'groups'
    distributionGroupId: '0398fe91-8d72-4af4-8aed-9e9b8757d985'
