# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macOS 10.14'

variables:
  - group: iOS_calc

- job: build
  displayName: Building .ipa
  dependsOn: test
  steps:
  - script: pod install --project-directory=SwiftCalculator-master
    displayName: 'Install AppCenter'
    
  - task: Xcode@5
    inputs:
      xcWorkspacePath: 'SwiftCalculator-master/Calculator.xcworkspace'
      scheme: 'Calculator'
      sdk: 'iphoneos'
      configuration: 'Release'
      xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
    
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: '$(p12name)'
      certPwd: '$(p12pass)'
      keychain: 'temp' # Options: default, temp, custom
      deleteCert: true
    
